apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-server-helm.fullname" . }}
  labels:
    kubernetes.io/name: "Metrics-server"
    kubernetes.io/cluster-service: "true"
    {{- include "metrics-server-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: main-port
      protocol: TCP
  selector:
    {{- include "metrics-server-helm.selectorLabels" . | nindent 4 }}
